# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telegram_com.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12telegram_com.proto\x12\x0ctelegram_com\"C\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x14\n\x07\x65\x64it_id\x18\x02 \x01(\x03H\x00\x88\x01\x01\x42\n\n\x08_edit_id\"\x1f\n\tMessageID\x12\x12\n\nmessage_id\x18\x01 \x01(\x03\x32Z\n\x10TelegramRepeater\x12\x46\n\x0bSendMessage\x12\x1c.telegram_com.MessageRequest\x1a\x17.telegram_com.MessageID\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telegram_com_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGEREQUEST']._serialized_start=36
  _globals['_MESSAGEREQUEST']._serialized_end=103
  _globals['_MESSAGEID']._serialized_start=105
  _globals['_MESSAGEID']._serialized_end=136
  _globals['_TELEGRAMREPEATER']._serialized_start=138
  _globals['_TELEGRAMREPEATER']._serialized_end=228
# @@protoc_insertion_point(module_scope)
